repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort

