[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
skip-string-normalization = true

[tool.isort]
profile = "black"
skip_glob = ["migrations", "**/__init__.py"]
line_length = 119
skip_gitignore = true
known_first_party = ["api_server", "integration"]
force_sort_within_sections = true
